version: '3.8'

services:
  yolo-demo:
    image: yolo-demo:latest
    container_name: yolo-demo-dev
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      # Uncomment this if required
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - UID=1000
      - GID=1000
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /dev/shm:/dev/shm
      - .:/yolo  # Mount the local codebase to /app in the container
    ports:
      - "8080:8080"
      - "9229:9229"  # Additional port for debugging, if needed
    network_mode: host
    # command: tail -f /dev/null  #  Keep the container running
    entrypoint: ["/bin/bash", "yolo_entrypoint.sh"]

    # command: ["/bin/bash"]
    # # Add any start command you need here, the above command is just an example.

  isaac-sim:
    image: isaac-sim:custom-build
    container_name: isaac-sim-dev
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - UID=1000
      - GID=1000
    volumes:
      - ~/docker/isaac-sim/cache/kit:/isaac-sim/kit/cache:rw
      - ~/docker/isaac-sim/cache/ov:/root/.cache/ov:rw
      - ~/docker/isaac-sim/cache/pip:/root/.cache/pip:rw
      - ~/docker/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ~/docker/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
      - ~/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
      - ~/docker/isaac-sim/data:/root/.local/share/ov/data:rw
      - ~/docker/isaac-sim/documents:/root/Documents:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /dev/shm:/dev/shm
      - ./isaac-sim/humble_ws:/isaac-sim/humble_ws  # Mount your codebase to /workspace
    ports:
      - "47995:47995"
      - "8000:8000"  # Additional port for dev/debug server
    network_mode: host
    entrypoint: ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && ./runheadless.native.sh"]
    # Modify this start command as needed for Isaac Sim.

  llama:
    image: llama:latest
    container_name: llama-dev
    runtime: nvidia
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - PULSE_SERVER=unix:/tmp/pulse_socket
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd  # Audio devices (added)
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/pulse_socket:/tmp/pulse_socket:ro 
      - ./llama:/llama
    ports:
      - "8080:8080"
    network_mode: host
    command: tail -f /dev/null
    # entrypoint: ["/bin/bash", "llama_entrypoint.sh"]

    # Modify this start command as needed for Isaac Sim.